### 목표 평가 (1)
POST localhost:8080/goal
Content-Type: application/json
Accept: application/json

{
  "text": "부자되기"
}

### 목표 평가 (2)
POST localhost:8080/goal
Content-Type: application/json
Accept: application/json

{
  "text": "2026년 6월 30일까지 체지방률을 25%에서 18%로 줄인다"
}

### 대화 시작
POST localhost:8080/chat/test1
Content-Type: text/plain

부자되기