version: '3.9'

services:
  aiminder-database:
    image: postgres:14
    container_name: aiminder-database
    environment:
      POSTGRES_DB: "aiminderdb"
      POSTGRES_USER: "aiminder"
      POSTGRES_PASSWORD: "aiminder"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  aiminder-application:
    image: aiminder-backend-app:latest
    build:
      context: .
    container_name: aiminder-application
    depends_on:
      - aiminder-database
    environment:
      - DATABASE_URL=r2dbc:postgresql://aiminder-database:5432/aiminderdb
      - SPRING_PROFILES_ACTIVE=dev,openai
    ports:
      - "8080:8080"
    restart: always